# Generated by Django 3.2.4 on 2021-08-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.TextField(blank=True)),
                ('intolerance', models.TextField(blank=True)),
                ('favourite1', models.CharField(max_length=100)),
                ('favourite2', models.CharField(max_length=100)),
                ('favourite3', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
