# Generated by Django 3.2.4 on 2021-08-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fullname',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
