# Generated by Django 3.2.4 on 2021-08-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_info_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='fullname',
        ),
    ]
