# Generated by Django 3.2.4 on 2021-08-22 15:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0004_alter_info_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='info',
            managers=[
                ('postObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
