# Generated by Django 3.2.4 on 2021-08-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_alter_info_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='info',
            managers=[
            ],
        ),
    ]
